classDiagram
class EtageList {
  +forretningshændelse
  +forretningsområde
  +forretningsproces
  +id_namespace
  +id_lokalId
  +kommunekode
  +registreringFra
  +registreringsaktør
  +registreringTil
  +virkningFra
  +virkningsaktør
  +virkningTil
  +status
  +eta006BygningensEtagebetegnelse
  +eta020SamletArealAfEtage
  +eta021ArealAfUdnyttetDelAfTagetage
  +eta022Kælderareal
  +eta023ArealAfLovligBeboelseIKælder
  +eta024EtagensAdgangsareal
  +eta025Etagetype
  +eta026ErhvervIKælder
  +eta500Notatlinjer
  +bygning
}