classDiagram
class FordelingsarealList {
  +forretningshændelse
  +forretningsområde
  +forretningsproces
  +id_namespace
  +id_lokalId
  +kommunekode
  +registreringFra
  +registreringsaktør
  +registreringTil
  +virkningFra
  +virkningsaktør
  +virkningTil
  +status
  +for002Fordelingsarealnummer
  +for003ArealTilFordeling
  +for004FordelingsNøgle
  +for500Notatlinjer
  +for005Navn
  +for006Rest
  +bygning
}