classDiagram
class EnhedList {
  +forretningshændelse
  +forretningsområde
  +forretningsproces
  +id_namespace
  +id_lokalId
  +kommunekode
  +registreringFra
  +registreringsaktør
  +registreringTil
  +virkningFra
  +virkningsaktør
  +virkningTil
  +status
  +enh008UUIDTilModerlejlighed
  +enh020EnhedensAnvendelse
  +enh023Boligtype
  +enh024KondemneretBoligenhed
  +enh025OprettelsesdatoForEnhedensIdentifikation
  +enh026EnhedensSamledeAreal
  +enh027ArealTilBeboelse
  +enh028ArealTilErhverv
  +enh030KildeTilEnhedensArealer
  +enh031AntalVærelser
  +enh032Toiletforhold
  +enh033Badeforhold
  +enh034Køkkenforhold
  +enh035Energiforsyning
  +enh039AndetAreal
  +enh041LovligAnvendelse
  +enh042DatoForTidsbegrænsetDispensation
  +enh044DatoForDelvisIbrugtagningsTilladelse
  +enh045Udlejningsforhold
  +enh046OffentligStøtte
  +enh047IndflytningDato
  +enh048GodkendtTomBolig
  +enh051Varmeinstallation
  +enh052Opvarmningsmiddel
  +enh053SupplerendeVarme
  +enh060EnhedensAndelFællesAdgangsareal
  +enh061ArealAfÅbenOverdækning
  +enh062ArealAfLukketOverdækningUdestue
  +enh063AntalVærelserTilErhverv
  +enh065AntalVandskylledeToiletter
  +enh066AntalBadeværelser
  +enh067Støjisolering
  +enh101Gyldighedsdato
  +enh127FysiskArealTilBeboelse
  +enh128FysiskArealTilErhverv
  +enh500Notatlinjer
  +enh068FlexboligTilladelsesart
  +enh069FlexboligOphørsdato
  +enh070ÅbenAltanTagterrasseAreal
  +enh102HerafAreal1
  +enh103HerafAreal2
  +enh104HerafAreal3
  +enh105SupplerendeAnvendelseskode1
  +enh106SupplerendeAnvendelseskode2
  +enh107SupplerendeAnvendelseskode3
  +enh071AdresseFunktion
  +adresseIdentificerer
  +etage
  +opgang
  +bygning
}