classDiagram
class EnhedEjendomsrelationList {
  +forretningshændelse
  +forretningsområde
  +forretningsproces
  +id_namespace
  +id_lokalId
  +kommunekode
  +registreringFra
  +registreringsaktør
  +registreringTil
  +virkningFra
  +virkningsaktør
  +virkningTil
  +status
  +ejerlejlighed
  +enhed
}