classDiagram
class EjendomsrelationList {
  +forretningshændelse
  +forretningsområde
  +forretningsproces
  +id_namespace
  +id_lokalId
  +kommunekode
  +registreringFra
  +registreringsaktør
  +registreringTil
  +virkningFra
  +virkningsaktør
  +virkningTil
  +status
  +bfeNummer
  +ejendommensEjerforholdskode
  +ejendomsnummer
  +vurderingsejendomsnummer
  +ejerlejlighedsnummer
  +ejendomstype
  +tinglystAreal
  +bygningPåFremmedGrund
  +ejerlejlighed
  +samletFastEjendom
}