classDiagram
class FordelingAfFordelingsarealList {
  +forretningshændelse
  +forretningsområde
  +forretningsproces
  +id_namespace
  +id_lokalId
  +kommunekode
  +registreringFra
  +registreringsaktør
  +registreringTil
  +virkningFra
  +virkningsaktør
  +virkningTil
  +status
  +beboelsesArealFordeltTilEnhed
  +erhvervsArealFordeltTilEnhed
  +enhed
  +fordelingsareal
}